nginx:
    build: ./front-end-server
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./back-end-server
    links:
        - redis
    ports:
        - "8080"
node2:
    build: ./back-end-server
    links:
        - redis
    ports:
        - "8080"
node3:
    build: ./back-end-server
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
postgres:
    build: ./database
    ports:
        - "5432:5432"
pythonWorker:
    build: ./service-worker
    links:
        - postgres
        - redis
